Output ../slides/assets/tape_outputs/rvasec_websearch_struct_0.gif
Output ../slides/assets/tape_outputs/rvasec_websearch_struct_0.mp4

Set Shell bash
Set Padding 1
Set TypingSpeed 2ms
Set FontSize 30
Set Width 1500
Set Height 800


Hide
Type cd ../src/
Enter
Show

Type 'uv --directory . --project ../../EXTERNAL/smolagents/ run smolagent "what is the rvasec conference?"  --model-type "LiteLLMModel" --model-id "ollama/qwen2.5-coder:14b-instruct-q4_K_M" --imports "pandas numpy" --tools "web_search" --api-base "http://fractal:11434" --api-key "lolnoproblem"'

Enter

#Wait+Screen@60s /Final/
#Wait+Line@15s /\[morgan\@framey/
Wait+Line@25s

# Clear the lines so that the last text is visible when the video is paused
Enter
Enter

